config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # devise_for :users

  # support Facebook canvas post
  post '/' => 'songs#index'

  resources :data_files, path: :data, only: [:show]
  resources :songs_list, path: :karaoke_list, only: [:show]
  resources :songs, path: :karaoke, only: [:index, :show]

  get '/muoi_bai_nhieu_nguoi_hat_nhat' => 'songs#index', q: 'most_viewed', filter: 'most_viewed'
  get '/muoi_bai_karaoke_hay' => 'songs#index', q: { featured_eq: 1 }, filter: 'featured'
  get '/muoi_bai_karaoke_ngau_nhien' => 'songs#index', q: 'random', filter: 'random'
  get '/muoi_bai_karaoke_song_ca' => 'songs#index',
      q: { man_supported_and_woman_supported_eq: 1 }, filter: 'man_and_woman'
  get '/muoi_bai_karaoke_giong_nam' => 'songs#index', q: { man_supported_eq: 1, woman_supported_eq: 0 }, filter: 'man'
  get '/muoi_bai_karaoke_giong_nu' => 'songs#index', q: { woman_supported_eq: 1, man_supported_eq: 0 }, filter: 'woman'

  get '/songs_map' => 'sitemap#index', format: :xml

  root 'songs#index'
end

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-8015694-14', 'auto');
  ga('set', 'userId', '<%= request.session[:session_id] %>'); // Set the user ID using signed-in user_id.
  ga('send', 'pageview');

</script>

app/views/shared/_facebook_connect.html.erb
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.8&appId=<%= ENV['FB_APP_ID'] %>";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

app/views/shared/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_go_away_modal.html.erb
<div id="go-away-modal" class="ui fullscreen modal">
  <div class="header"><i class="warning circle icon"></i> Nội dung bị chặn</div>
  <div class="content">
    <div class="ui error message">
      <div class="header">
        Trang web bị chặn bởi các công cụ AdBlock, AdBlocker hoặc các công cụ tương tự:
      </div>
      <ul class="list">
        <li>Xin vui lòng gỡ bỏ các công cụ AdBlock và truy cập lại để tiếp tục.</li>
        <li>Hướng dẫn gỡ bỏ tiện ích cài thêm cho trình duyệt Chrome: <a href="https://support.google.com/chrome_webstore/answer/2664769?hl=vi">Cài đặt và quản lý tiện ích</a>.</li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_letters.html.erb
<h4 class="ui header text center">
  <% letters.each_pair do |letter, _count| %>
    <%= link_to letter.upcase, songs_list_path(letter), class: 'songs-list-letter' %>
  <% end %>
</h4>

app/views/shared/_open_graph.html.erb
<meta property="fb:app_id" content="<%= ENV['FB_APP_ID'] %>" />
<meta property="og:url" content="<%= app_current_url %>" />
<meta property="og:type" content="<%= og_type %>" />
<meta property="og:title" content="<%= app_title %>" />
<meta property="og:description" content="<%= app_description %>" />
<meta property="og:image" content="<%= image_url 'mic_small.png' %>" />

app/views/shared/_top_menu.html.erb
<div class="ui one column centered grid container">
  <div class="column">
    <%= react_component('TopMenu', { currentUser: nil }, { prerender: true }) %>
  </div>

  <div class="tablet computer only column">
    <%= render 'shared/letters', letters: @letters %>
  </div>

  <div class="six wide computer sixteen wide mobile column">
    <%= react_component('SearchMenu', { currentUser: nil }, { prerender: true }) %>
  </div>
</div>